version: '3'
services:
  websocket-server:
    build:
      context: ./server
    ports:
      - "9080:9080"
    container_name: websocket-server
    volumes:
       - ./server:/server
       - /server/node_modules
  react-client:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react-client
    stdin_open: true
    volumes:
       - ./src:/src
       - /node_modules